services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./runs:/app/runs
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    stdin_open: true
    tty: true
    command: tail -f /dev/null

volumes:
  data:
  src:
  runs:
